//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace front_end.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfMarca", Namespace="http://tempuri.org/", ItemName="marca")]
    [System.SerializableAttribute()]
    public class ArrayOfMarca : System.Collections.Generic.List<front_end.ServiceReference1.marca> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="marca", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class marca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long id_marcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private front_end.ServiceReference1.ArrayOfModelo modeloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id_marca {
            get {
                return this.id_marcaField;
            }
            set {
                if ((this.id_marcaField.Equals(value) != true)) {
                    this.id_marcaField = value;
                    this.RaisePropertyChanged("id_marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public front_end.ServiceReference1.ArrayOfModelo modelo {
            get {
                return this.modeloField;
            }
            set {
                if ((object.ReferenceEquals(this.modeloField, value) != true)) {
                    this.modeloField = value;
                    this.RaisePropertyChanged("modelo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfModelo", Namespace="http://tempuri.org/", ItemName="modelo")]
    [System.SerializableAttribute()]
    public class ArrayOfModelo : System.Collections.Generic.List<front_end.ServiceReference1.modelo> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="modelo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class modelo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_modeloField;
        
        private System.Nullable<long> id_marcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string id_modelo {
            get {
                return this.id_modeloField;
            }
            set {
                if ((object.ReferenceEquals(this.id_modeloField, value) != true)) {
                    this.id_modeloField = value;
                    this.RaisePropertyChanged("id_modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<long> id_marca {
            get {
                return this.id_marcaField;
            }
            set {
                if ((this.id_marcaField.Equals(value) != true)) {
                    this.id_marcaField = value;
                    this.RaisePropertyChanged("id_marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO_Marca", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DTO_Marca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long id_marcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id_marca {
            get {
                return this.id_marcaField;
            }
            set {
                if ((this.id_marcaField.Equals(value) != true)) {
                    this.id_marcaField = value;
                    this.RaisePropertyChanged("id_marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                if ((object.ReferenceEquals(this.modeloField, value) != true)) {
                    this.modeloField = value;
                    this.RaisePropertyChanged("modelo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServicioWeb_MarcaSoap")]
    public interface ServicioWeb_MarcaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SeleccionarMarcasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarMarcas", ReplyAction="*")]
        front_end.ServiceReference1.SeleccionarMarcasResponse SeleccionarMarcas(front_end.ServiceReference1.SeleccionarMarcasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarMarcas", ReplyAction="*")]
        System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcasResponse> SeleccionarMarcasAsync(front_end.ServiceReference1.SeleccionarMarcasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SeleccionarMarcasModelosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarMarcasModelos", ReplyAction="*")]
        front_end.ServiceReference1.SeleccionarMarcasModelosResponse SeleccionarMarcasModelos(front_end.ServiceReference1.SeleccionarMarcasModelosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarMarcasModelos", ReplyAction="*")]
        System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcasModelosResponse> SeleccionarMarcasModelosAsync(front_end.ServiceReference1.SeleccionarMarcasModelosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SeleccionarMarcaModelosLinqResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarMarcaModelosLinq", ReplyAction="*")]
        front_end.ServiceReference1.SeleccionarMarcaModelosLinqResponse SeleccionarMarcaModelosLinq(front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarMarcaModelosLinq", ReplyAction="*")]
        System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcaModelosLinqResponse> SeleccionarMarcaModelosLinqAsync(front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SeleccionarMarcaModelosID_DTOResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarMarcaModelosID_DTO", ReplyAction="*")]
        front_end.ServiceReference1.SeleccionarMarcaModelosID_DTOResponse SeleccionarMarcaModelosID_DTO(front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SeleccionarMarcaModelosID_DTO", ReplyAction="*")]
        System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcaModelosID_DTOResponse> SeleccionarMarcaModelosID_DTOAsync(front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nuevo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarMarca", ReplyAction="*")]
        front_end.ServiceReference1.InsertarMarcaResponse InsertarMarca(front_end.ServiceReference1.InsertarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<front_end.ServiceReference1.InsertarMarcaResponse> InsertarMarcaAsync(front_end.ServiceReference1.InsertarMarcaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento actualizar del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarMarca", ReplyAction="*")]
        front_end.ServiceReference1.ActualizarMarcaResponse ActualizarMarca(front_end.ServiceReference1.ActualizarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<front_end.ServiceReference1.ActualizarMarcaResponse> ActualizarMarcaAsync(front_end.ServiceReference1.ActualizarMarcaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento eliminar del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarMarca", ReplyAction="*")]
        front_end.ServiceReference1.EliminarMarcaResponse EliminarMarca(front_end.ServiceReference1.EliminarMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<front_end.ServiceReference1.EliminarMarcaResponse> EliminarMarcaAsync(front_end.ServiceReference1.EliminarMarcaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarMarcasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarMarcas", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.SeleccionarMarcasRequestBody Body;
        
        public SeleccionarMarcasRequest() {
        }
        
        public SeleccionarMarcasRequest(front_end.ServiceReference1.SeleccionarMarcasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SeleccionarMarcasRequestBody {
        
        public SeleccionarMarcasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarMarcasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarMarcasResponse", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.SeleccionarMarcasResponseBody Body;
        
        public SeleccionarMarcasResponse() {
        }
        
        public SeleccionarMarcasResponse(front_end.ServiceReference1.SeleccionarMarcasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarMarcasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public front_end.ServiceReference1.ArrayOfMarca SeleccionarMarcasResult;
        
        public SeleccionarMarcasResponseBody() {
        }
        
        public SeleccionarMarcasResponseBody(front_end.ServiceReference1.ArrayOfMarca SeleccionarMarcasResult) {
            this.SeleccionarMarcasResult = SeleccionarMarcasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarMarcasModelosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarMarcasModelos", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.SeleccionarMarcasModelosRequestBody Body;
        
        public SeleccionarMarcasModelosRequest() {
        }
        
        public SeleccionarMarcasModelosRequest(front_end.ServiceReference1.SeleccionarMarcasModelosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SeleccionarMarcasModelosRequestBody {
        
        public SeleccionarMarcasModelosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarMarcasModelosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarMarcasModelosResponse", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.SeleccionarMarcasModelosResponseBody Body;
        
        public SeleccionarMarcasModelosResponse() {
        }
        
        public SeleccionarMarcasModelosResponse(front_end.ServiceReference1.SeleccionarMarcasModelosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarMarcasModelosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public front_end.ServiceReference1.ArrayOfMarca SeleccionarMarcasModelosResult;
        
        public SeleccionarMarcasModelosResponseBody() {
        }
        
        public SeleccionarMarcasModelosResponseBody(front_end.ServiceReference1.ArrayOfMarca SeleccionarMarcasModelosResult) {
            this.SeleccionarMarcasModelosResult = SeleccionarMarcasModelosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarMarcaModelosLinqRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarMarcaModelosLinq", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequestBody Body;
        
        public SeleccionarMarcaModelosLinqRequest() {
        }
        
        public SeleccionarMarcaModelosLinqRequest(front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SeleccionarMarcaModelosLinqRequestBody {
        
        public SeleccionarMarcaModelosLinqRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarMarcaModelosLinqResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarMarcaModelosLinqResponse", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.SeleccionarMarcaModelosLinqResponseBody Body;
        
        public SeleccionarMarcaModelosLinqResponse() {
        }
        
        public SeleccionarMarcaModelosLinqResponse(front_end.ServiceReference1.SeleccionarMarcaModelosLinqResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarMarcaModelosLinqResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public front_end.ServiceReference1.ArrayOfMarca SeleccionarMarcaModelosLinqResult;
        
        public SeleccionarMarcaModelosLinqResponseBody() {
        }
        
        public SeleccionarMarcaModelosLinqResponseBody(front_end.ServiceReference1.ArrayOfMarca SeleccionarMarcaModelosLinqResult) {
            this.SeleccionarMarcaModelosLinqResult = SeleccionarMarcaModelosLinqResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarMarcaModelosID_DTORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarMarcaModelosID_DTO", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequestBody Body;
        
        public SeleccionarMarcaModelosID_DTORequest() {
        }
        
        public SeleccionarMarcaModelosID_DTORequest(front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarMarcaModelosID_DTORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idMarca;
        
        public SeleccionarMarcaModelosID_DTORequestBody() {
        }
        
        public SeleccionarMarcaModelosID_DTORequestBody(int idMarca) {
            this.idMarca = idMarca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SeleccionarMarcaModelosID_DTOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SeleccionarMarcaModelosID_DTOResponse", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.SeleccionarMarcaModelosID_DTOResponseBody Body;
        
        public SeleccionarMarcaModelosID_DTOResponse() {
        }
        
        public SeleccionarMarcaModelosID_DTOResponse(front_end.ServiceReference1.SeleccionarMarcaModelosID_DTOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SeleccionarMarcaModelosID_DTOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public front_end.ServiceReference1.DTO_Marca SeleccionarMarcaModelosID_DTOResult;
        
        public SeleccionarMarcaModelosID_DTOResponseBody() {
        }
        
        public SeleccionarMarcaModelosID_DTOResponseBody(front_end.ServiceReference1.DTO_Marca SeleccionarMarcaModelosID_DTOResult) {
            this.SeleccionarMarcaModelosID_DTOResult = SeleccionarMarcaModelosID_DTOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarMarca", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.InsertarMarcaRequestBody Body;
        
        public InsertarMarcaRequest() {
        }
        
        public InsertarMarcaRequest(front_end.ServiceReference1.InsertarMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarMarcaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public front_end.ServiceReference1.marca nuevo;
        
        public InsertarMarcaRequestBody() {
        }
        
        public InsertarMarcaRequestBody(front_end.ServiceReference1.marca nuevo) {
            this.nuevo = nuevo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarMarcaResponse", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.InsertarMarcaResponseBody Body;
        
        public InsertarMarcaResponse() {
        }
        
        public InsertarMarcaResponse(front_end.ServiceReference1.InsertarMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public front_end.ServiceReference1.marca InsertarMarcaResult;
        
        public InsertarMarcaResponseBody() {
        }
        
        public InsertarMarcaResponseBody(front_end.ServiceReference1.marca InsertarMarcaResult) {
            this.InsertarMarcaResult = InsertarMarcaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarMarca", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.ActualizarMarcaRequestBody Body;
        
        public ActualizarMarcaRequest() {
        }
        
        public ActualizarMarcaRequest(front_end.ServiceReference1.ActualizarMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarMarcaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public front_end.ServiceReference1.marca actualizar;
        
        public ActualizarMarcaRequestBody() {
        }
        
        public ActualizarMarcaRequestBody(front_end.ServiceReference1.marca actualizar) {
            this.actualizar = actualizar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarMarcaResponse", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.ActualizarMarcaResponseBody Body;
        
        public ActualizarMarcaResponse() {
        }
        
        public ActualizarMarcaResponse(front_end.ServiceReference1.ActualizarMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarMarcaResult;
        
        public ActualizarMarcaResponseBody() {
        }
        
        public ActualizarMarcaResponseBody(bool ActualizarMarcaResult) {
            this.ActualizarMarcaResult = ActualizarMarcaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarMarca", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.EliminarMarcaRequestBody Body;
        
        public EliminarMarcaRequest() {
        }
        
        public EliminarMarcaRequest(front_end.ServiceReference1.EliminarMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarMarcaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public front_end.ServiceReference1.marca eliminar;
        
        public EliminarMarcaRequestBody() {
        }
        
        public EliminarMarcaRequestBody(front_end.ServiceReference1.marca eliminar) {
            this.eliminar = eliminar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarMarcaResponse", Namespace="http://tempuri.org/", Order=0)]
        public front_end.ServiceReference1.EliminarMarcaResponseBody Body;
        
        public EliminarMarcaResponse() {
        }
        
        public EliminarMarcaResponse(front_end.ServiceReference1.EliminarMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarMarcaResult;
        
        public EliminarMarcaResponseBody() {
        }
        
        public EliminarMarcaResponseBody(bool EliminarMarcaResult) {
            this.EliminarMarcaResult = EliminarMarcaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWeb_MarcaSoapChannel : front_end.ServiceReference1.ServicioWeb_MarcaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWeb_MarcaSoapClient : System.ServiceModel.ClientBase<front_end.ServiceReference1.ServicioWeb_MarcaSoap>, front_end.ServiceReference1.ServicioWeb_MarcaSoap {
        
        public ServicioWeb_MarcaSoapClient() {
        }
        
        public ServicioWeb_MarcaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWeb_MarcaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWeb_MarcaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWeb_MarcaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        front_end.ServiceReference1.SeleccionarMarcasResponse front_end.ServiceReference1.ServicioWeb_MarcaSoap.SeleccionarMarcas(front_end.ServiceReference1.SeleccionarMarcasRequest request) {
            return base.Channel.SeleccionarMarcas(request);
        }
        
        public front_end.ServiceReference1.ArrayOfMarca SeleccionarMarcas() {
            front_end.ServiceReference1.SeleccionarMarcasRequest inValue = new front_end.ServiceReference1.SeleccionarMarcasRequest();
            inValue.Body = new front_end.ServiceReference1.SeleccionarMarcasRequestBody();
            front_end.ServiceReference1.SeleccionarMarcasResponse retVal = ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).SeleccionarMarcas(inValue);
            return retVal.Body.SeleccionarMarcasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcasResponse> front_end.ServiceReference1.ServicioWeb_MarcaSoap.SeleccionarMarcasAsync(front_end.ServiceReference1.SeleccionarMarcasRequest request) {
            return base.Channel.SeleccionarMarcasAsync(request);
        }
        
        public System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcasResponse> SeleccionarMarcasAsync() {
            front_end.ServiceReference1.SeleccionarMarcasRequest inValue = new front_end.ServiceReference1.SeleccionarMarcasRequest();
            inValue.Body = new front_end.ServiceReference1.SeleccionarMarcasRequestBody();
            return ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).SeleccionarMarcasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        front_end.ServiceReference1.SeleccionarMarcasModelosResponse front_end.ServiceReference1.ServicioWeb_MarcaSoap.SeleccionarMarcasModelos(front_end.ServiceReference1.SeleccionarMarcasModelosRequest request) {
            return base.Channel.SeleccionarMarcasModelos(request);
        }
        
        public front_end.ServiceReference1.ArrayOfMarca SeleccionarMarcasModelos() {
            front_end.ServiceReference1.SeleccionarMarcasModelosRequest inValue = new front_end.ServiceReference1.SeleccionarMarcasModelosRequest();
            inValue.Body = new front_end.ServiceReference1.SeleccionarMarcasModelosRequestBody();
            front_end.ServiceReference1.SeleccionarMarcasModelosResponse retVal = ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).SeleccionarMarcasModelos(inValue);
            return retVal.Body.SeleccionarMarcasModelosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcasModelosResponse> front_end.ServiceReference1.ServicioWeb_MarcaSoap.SeleccionarMarcasModelosAsync(front_end.ServiceReference1.SeleccionarMarcasModelosRequest request) {
            return base.Channel.SeleccionarMarcasModelosAsync(request);
        }
        
        public System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcasModelosResponse> SeleccionarMarcasModelosAsync() {
            front_end.ServiceReference1.SeleccionarMarcasModelosRequest inValue = new front_end.ServiceReference1.SeleccionarMarcasModelosRequest();
            inValue.Body = new front_end.ServiceReference1.SeleccionarMarcasModelosRequestBody();
            return ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).SeleccionarMarcasModelosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        front_end.ServiceReference1.SeleccionarMarcaModelosLinqResponse front_end.ServiceReference1.ServicioWeb_MarcaSoap.SeleccionarMarcaModelosLinq(front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequest request) {
            return base.Channel.SeleccionarMarcaModelosLinq(request);
        }
        
        public front_end.ServiceReference1.ArrayOfMarca SeleccionarMarcaModelosLinq() {
            front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequest inValue = new front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequest();
            inValue.Body = new front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequestBody();
            front_end.ServiceReference1.SeleccionarMarcaModelosLinqResponse retVal = ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).SeleccionarMarcaModelosLinq(inValue);
            return retVal.Body.SeleccionarMarcaModelosLinqResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcaModelosLinqResponse> front_end.ServiceReference1.ServicioWeb_MarcaSoap.SeleccionarMarcaModelosLinqAsync(front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequest request) {
            return base.Channel.SeleccionarMarcaModelosLinqAsync(request);
        }
        
        public System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcaModelosLinqResponse> SeleccionarMarcaModelosLinqAsync() {
            front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequest inValue = new front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequest();
            inValue.Body = new front_end.ServiceReference1.SeleccionarMarcaModelosLinqRequestBody();
            return ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).SeleccionarMarcaModelosLinqAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        front_end.ServiceReference1.SeleccionarMarcaModelosID_DTOResponse front_end.ServiceReference1.ServicioWeb_MarcaSoap.SeleccionarMarcaModelosID_DTO(front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequest request) {
            return base.Channel.SeleccionarMarcaModelosID_DTO(request);
        }
        
        public front_end.ServiceReference1.DTO_Marca SeleccionarMarcaModelosID_DTO(int idMarca) {
            front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequest inValue = new front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequest();
            inValue.Body = new front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequestBody();
            inValue.Body.idMarca = idMarca;
            front_end.ServiceReference1.SeleccionarMarcaModelosID_DTOResponse retVal = ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).SeleccionarMarcaModelosID_DTO(inValue);
            return retVal.Body.SeleccionarMarcaModelosID_DTOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcaModelosID_DTOResponse> front_end.ServiceReference1.ServicioWeb_MarcaSoap.SeleccionarMarcaModelosID_DTOAsync(front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequest request) {
            return base.Channel.SeleccionarMarcaModelosID_DTOAsync(request);
        }
        
        public System.Threading.Tasks.Task<front_end.ServiceReference1.SeleccionarMarcaModelosID_DTOResponse> SeleccionarMarcaModelosID_DTOAsync(int idMarca) {
            front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequest inValue = new front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequest();
            inValue.Body = new front_end.ServiceReference1.SeleccionarMarcaModelosID_DTORequestBody();
            inValue.Body.idMarca = idMarca;
            return ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).SeleccionarMarcaModelosID_DTOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        front_end.ServiceReference1.InsertarMarcaResponse front_end.ServiceReference1.ServicioWeb_MarcaSoap.InsertarMarca(front_end.ServiceReference1.InsertarMarcaRequest request) {
            return base.Channel.InsertarMarca(request);
        }
        
        public front_end.ServiceReference1.marca InsertarMarca(front_end.ServiceReference1.marca nuevo) {
            front_end.ServiceReference1.InsertarMarcaRequest inValue = new front_end.ServiceReference1.InsertarMarcaRequest();
            inValue.Body = new front_end.ServiceReference1.InsertarMarcaRequestBody();
            inValue.Body.nuevo = nuevo;
            front_end.ServiceReference1.InsertarMarcaResponse retVal = ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).InsertarMarca(inValue);
            return retVal.Body.InsertarMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<front_end.ServiceReference1.InsertarMarcaResponse> front_end.ServiceReference1.ServicioWeb_MarcaSoap.InsertarMarcaAsync(front_end.ServiceReference1.InsertarMarcaRequest request) {
            return base.Channel.InsertarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<front_end.ServiceReference1.InsertarMarcaResponse> InsertarMarcaAsync(front_end.ServiceReference1.marca nuevo) {
            front_end.ServiceReference1.InsertarMarcaRequest inValue = new front_end.ServiceReference1.InsertarMarcaRequest();
            inValue.Body = new front_end.ServiceReference1.InsertarMarcaRequestBody();
            inValue.Body.nuevo = nuevo;
            return ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).InsertarMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        front_end.ServiceReference1.ActualizarMarcaResponse front_end.ServiceReference1.ServicioWeb_MarcaSoap.ActualizarMarca(front_end.ServiceReference1.ActualizarMarcaRequest request) {
            return base.Channel.ActualizarMarca(request);
        }
        
        public bool ActualizarMarca(front_end.ServiceReference1.marca actualizar) {
            front_end.ServiceReference1.ActualizarMarcaRequest inValue = new front_end.ServiceReference1.ActualizarMarcaRequest();
            inValue.Body = new front_end.ServiceReference1.ActualizarMarcaRequestBody();
            inValue.Body.actualizar = actualizar;
            front_end.ServiceReference1.ActualizarMarcaResponse retVal = ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).ActualizarMarca(inValue);
            return retVal.Body.ActualizarMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<front_end.ServiceReference1.ActualizarMarcaResponse> front_end.ServiceReference1.ServicioWeb_MarcaSoap.ActualizarMarcaAsync(front_end.ServiceReference1.ActualizarMarcaRequest request) {
            return base.Channel.ActualizarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<front_end.ServiceReference1.ActualizarMarcaResponse> ActualizarMarcaAsync(front_end.ServiceReference1.marca actualizar) {
            front_end.ServiceReference1.ActualizarMarcaRequest inValue = new front_end.ServiceReference1.ActualizarMarcaRequest();
            inValue.Body = new front_end.ServiceReference1.ActualizarMarcaRequestBody();
            inValue.Body.actualizar = actualizar;
            return ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).ActualizarMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        front_end.ServiceReference1.EliminarMarcaResponse front_end.ServiceReference1.ServicioWeb_MarcaSoap.EliminarMarca(front_end.ServiceReference1.EliminarMarcaRequest request) {
            return base.Channel.EliminarMarca(request);
        }
        
        public bool EliminarMarca(front_end.ServiceReference1.marca eliminar) {
            front_end.ServiceReference1.EliminarMarcaRequest inValue = new front_end.ServiceReference1.EliminarMarcaRequest();
            inValue.Body = new front_end.ServiceReference1.EliminarMarcaRequestBody();
            inValue.Body.eliminar = eliminar;
            front_end.ServiceReference1.EliminarMarcaResponse retVal = ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).EliminarMarca(inValue);
            return retVal.Body.EliminarMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<front_end.ServiceReference1.EliminarMarcaResponse> front_end.ServiceReference1.ServicioWeb_MarcaSoap.EliminarMarcaAsync(front_end.ServiceReference1.EliminarMarcaRequest request) {
            return base.Channel.EliminarMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<front_end.ServiceReference1.EliminarMarcaResponse> EliminarMarcaAsync(front_end.ServiceReference1.marca eliminar) {
            front_end.ServiceReference1.EliminarMarcaRequest inValue = new front_end.ServiceReference1.EliminarMarcaRequest();
            inValue.Body = new front_end.ServiceReference1.EliminarMarcaRequestBody();
            inValue.Body.eliminar = eliminar;
            return ((front_end.ServiceReference1.ServicioWeb_MarcaSoap)(this)).EliminarMarcaAsync(inValue);
        }
    }
}
